# Generated by Django 5.1.5 on 2025-05-13 09:59

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=martor.models.MartorField(verbose_name='Текст'),
        ),
    ]
