# Generated by Django 5.1.5 on 2025-05-13 10:24

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=martor.models.MartorField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-адрес'),
        ),
    ]
