# Generated by Django 5.1.5 on 2025-06-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreaction',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(default='like', max_length=10),
        ),
    ]
